# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/domain/grpc_auth/protos/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&src/domain/grpc_auth/protos/auth.proto\x12\x0fgateway_backend\"\"\n\x0bPermissions\x12\x13\n\x0bpermissions\x18\x01 \x03(\t\"\x16\n\x05Roles\x12\r\n\x05roles\x18\x01 \x03(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"\x1b\n\x07IsValid\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\"\x17\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t2\x8e\x02\n\x04\x41uth\x12H\n\x0eGetPermissions\x12\x16.gateway_backend.Token\x1a\x1c.gateway_backend.Permissions\"\x00\x12<\n\x08GetRoles\x12\x16.gateway_backend.Token\x1a\x16.gateway_backend.Roles\"\x00\x12\x42\n\x0cIsAuthorized\x12\x16.gateway_backend.Token\x1a\x18.gateway_backend.IsValid\"\x00\x12:\n\x07GetUser\x12\x16.gateway_backend.Token\x1a\x15.gateway_backend.User\"\x00\x62\x06proto3')



_PERMISSIONS = DESCRIPTOR.message_types_by_name['Permissions']
_ROLES = DESCRIPTOR.message_types_by_name['Roles']
_TOKEN = DESCRIPTOR.message_types_by_name['Token']
_ISVALID = DESCRIPTOR.message_types_by_name['IsValid']
_USER = DESCRIPTOR.message_types_by_name['User']
Permissions = _reflection.GeneratedProtocolMessageType('Permissions', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONS,
  '__module__' : 'src.domain.grpc_auth.protos.auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Permissions)
  })
_sym_db.RegisterMessage(Permissions)

Roles = _reflection.GeneratedProtocolMessageType('Roles', (_message.Message,), {
  'DESCRIPTOR' : _ROLES,
  '__module__' : 'src.domain.grpc_auth.protos.auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Roles)
  })
_sym_db.RegisterMessage(Roles)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'src.domain.grpc_auth.protos.auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Token)
  })
_sym_db.RegisterMessage(Token)

IsValid = _reflection.GeneratedProtocolMessageType('IsValid', (_message.Message,), {
  'DESCRIPTOR' : _ISVALID,
  '__module__' : 'src.domain.grpc_auth.protos.auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.IsValid)
  })
_sym_db.RegisterMessage(IsValid)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'src.domain.grpc_auth.protos.auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.User)
  })
_sym_db.RegisterMessage(User)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERMISSIONS._serialized_start=59
  _PERMISSIONS._serialized_end=93
  _ROLES._serialized_start=95
  _ROLES._serialized_end=117
  _TOKEN._serialized_start=119
  _TOKEN._serialized_end=141
  _ISVALID._serialized_start=143
  _ISVALID._serialized_end=170
  _USER._serialized_start=172
  _USER._serialized_end=195
  _AUTH._serialized_start=198
  _AUTH._serialized_end=468
# @@protoc_insertion_point(module_scope)
