@startuml
skinparam componentStyle uml2
actor Client as client
actor Employee as employer

package "Movies Service" as movies{
    package "Admin Panel" as admin{
        component Nginx as adminNginx
        component Api as adminApi
        database "Movies Database" as moviesdb
    }
    package "Auth Service" as auth{
        component Nginx as authNginx
        component "Auth Api" as authApi
        database "Auth Database" as authdb
        database "Auth Cache" as authCache
    }
    package "Search Service" as search{
        component Nginx as searchNginx
        component SearchApi as searchApi
        database ElasticSearch
        component ETL as searchETL
    }
}


authApi -- authdb
authApi -- authCache
adminApi -- moviesdb
searchApi -- ElasticSearch

moviesdb -> searchETL
searchETL -> ElasticSearch

client <--> searchNginx : User Request
employer <--> adminNginx : DB Administration
adminNginx <--> adminApi
searchNginx <--> searchApi
authNginx <--> authApi
client <-> authNginx : Authorization
searchApi <-> authApi : Authentication

@enduml
